### ISSUE TITLE
Python GUI cannot connect to SPAD 

### ISSUE THREAD

**Issue by Jmeng3** [MattNolanLab/pySPAD#2]
Hi Kurtulus,

I can open the python GUI on my laptop but when I hit the 'connect' button, I receive the following TypeError: Wrong number or type of arguments for overloaded function 'okCFrontPanel_SetWireInValue' (see output messages below). 

Thank you for your support,
Julia

Welcome to SPADPhotometry!
----------------------------
Opal Kelly to Python Comms
----------------------------
True
Port is open
Configuration was accomplished!
*Firmware Revision:  64
Traceback (most recent call last):
  File "C:\Users\Julia Meng\code\pySPAD\GUI_main.py", line 79, in <lambda>
    lambda: self.disconnect() if self.connected else self.connect())
  File "C:\Users\Julia Meng\code\pySPAD\GUI_main.py", line 357, in connect
    self.sensor.SensorConnect(self.sensor.bank)
  File "C:\Users\Julia Meng\code\pySPAD\SPCIMAGERAA.py", line 162, in SensorConnect
    self.com.wireindata(bank, 'SPCIMAGER_CHIP_RESET', 1)
  File "C:\Users\Julia Meng\code\pySPAD\OK_Comms.py", line 258, in wireindata
    self.dev.SetWireInValue(address, d, mask)
  File "C:\Users\Julia Meng\code\pySPAD\config_files\ok.py", line 1241, in SetWireInValue
    return _ok.okCFrontPanel_SetWireInValue(self, *args)
TypeError: Wrong number or type of arguments for overloaded function 'okCFrontPanel_SetWireInValue'.
  Possible C/C++ prototypes are:
    OpalKellyLegacy::okCFrontPanel::SetWireInValue(int,UINT32,UINT32)
    OpalKellyLegacy::okCFrontPanel::SetWireInValue(int,UINT32)

**Comment by kurtulusbulus** [comment]
Hi Julia, 

Thanks for reporting this. 

This error usually occurs when Python cannot interpret OpalKelly librarires, which were written in C++. Just to make sure that everything was set up correctly, have you installed the Microsoft Redistributable packages that was mentioned in installation guide? 

_"As a last step, please make sure you have Microsoft Visual C++ Redistributable. You can setup this via the following link: https://www.microsoft.com/en-us/download/details.aspx?id=40784"_

Best, 

Kurtulus

**Comment by Jmeng3** [comment]
Hi Kurtulus,

Yes, I have installed the Microsoft redistributable packages. 

![Untitled](https://user-images.githubusercontent.com/115023345/212669615-04aa61e0-06dc-47e5-88ac-8aad851a5723.png)

Best,
Julia

**Comment by kurtulusbulus** [comment]
Hi Jula, 

I am sorry that you are having this problem and sorry for late response. I had to do a few seaches regarding the problem. 

I have searched Opal Kelly libraries and the problem seems from the code itself. However, we are also using the same code on our computers and the GUI is working fine. 

It strikes me that the problem might be that you are currently having several Python versions set up on your computer. We need to make sure that pySPAD environment is set up with Python version 3.7 and the GUI is running through on that specific version. Do you have any chance to check this? 

Best, 

Kurtulus

**Comment by Jmeng3** [comment]
Hi Kurtulus,

I had installed the 3.7 python version previously but for some unknown reason anaconda updated it to 3.10. I have now reverted the version back to 3.7 and I am now able to connect to the SPAD. Thank you so much! 

Best,
Julia

**Comment by kurtulusbulus** [comment]
Hi Julia, 

I am glad that the issue is solved! 

For Anaconda, that might be due to the fact that sometimes installing other packages in the environment automatically updates it to the specific version to prevent possible compatibility issues. To avoid this, I would recommend you to use pySPAD environment for only using SPAD camera, For your other tasks, you may create another environment and install the latest version of libraries that you would like to use. 

Anyway, thank you for using pySPAD and please keep reporting any isues and  providing feedback. It is really appreaciated. 

Best, 
Kurtulus
